import type { Metadata } from "next";
import "./globals.css";
import BodyLayout from "./body-layout";
import { Belleza, Inter, Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const belleza = Belleza({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-belleza",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(inter.variable, belleza.variable, montserrat.variable)}
    >
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        <BodyLayout>{children}</BodyLayout>
      </ThemeProvider>
    </html>
  );
}
