import type { Metadata } from "next";
import "./globals.css";
import BodyLayout from "./body-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BodyLayout>{children}</BodyLayout>
    </html>
  );
}
